# GENERATED BY BRILLIANT AR STUDIO Do not modify this file directly
import display as d

class arrows:
	screen=[
		d.Polygon([9,351,41,351,25,390], d.BLUE),
		d.Polygon([578,355,578,385,628,370], d.BLUE),
	]## dont't remove this #