# GENERATED BY BRILLIANT AR STUDIO Do not modify this file directly
import display as d

class logo:
	screen=[
		d.Rectangle(334, 8, 371, 126, 0xafafaf),
		d.Polygon([360,31,360,100,426,83,426,42,426,42,428,40], 0xafafaf),
		d.Rectangle(417, 28, 437, 97, 0xafafaf),
		d.Rectangle(322, 129, 449, 143, 0xafafaf),
		d.Line(331, 396, 437, 155, 0xafafaf, thickness=8),
		d.Line(331, 160, 443, 391, 0xafafaf, thickness=8),
		d.Polygon([325,5,322,117,308,163,305,224,308,276,294,278,271,247,251,261,233,224,248,166,276,68,299,28], 0xafafaf),
		d.Rectangle(431, 40, 446, 80, 0xafafaf),
	]## dont't remove this #